//--- UnitMenu
#define IDD_VEHMENU										1103
//--- Vehice
#define IDC_VEHICE_TEXT_VEHMENU_TITLE					1000
#define IDC_VEHICE_TEXT_VEHMENU_BG						1001
#define IDC_VEHICE_TEXT_VEHMENU_FUNDSTEXT				1002
#define IDC_VEHICE_TEXT_VEHMENU_FUNDSVALUE				1003
#define IDC_VEHICE_TEXT_VEHMENU_ALLVEHICLESAVAILABLE	1004
#define IDC_VEHICE_LB_VEHMENU_SELECTVEHICLE				1500
#define IDC_VEHICE_BUTTON_VEHMENU_BUYUNIT				1700
#define IDC_VEHICE_FRAME_VEHMENU_ACCOUNTDATA			1800

